# Generated by Django 5.0.2 on 2024-02-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clubs",
            name="members",
        ),
        migrations.AddField(
            model_name="accountrequests",
            name="contact_details",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="accountrequests",
            name="password",
            field=models.CharField(default=123, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="clubs",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
